name: project_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - tensorflow
  - tensorflow-gpu
  - cudatoolkit
  - cudnn
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - pillow
  - h5py
  - tqdm
  - requests
  - absl-py
  - protobuf
  - tensorflow-datasets
  - tensorflow-metadata
  - tensorboard
  - keras
  - dlib
  - jupyterlab
  - notebook
  - ipython
  - ipykernel
  - yaml
  - pyyaml
  - flask
  - lxml
  - six
  - werkzeug
  - pip:
      - grpcio==1.46.1
      - google-auth==2.17.1
      - google-auth-oauthlib==0.4.6
      - oauthlib==3.2.2
      - requests-oauthlib==1.3.1
      - cachetools==5.3.0
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - protobuf==3.19.6
      - rsa==4.9
      - termcolor==2.2.0
      - wrapt==1.15.0
      - zipp==3.15.0
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - markupsafe==2.1.2
      - markdown==3.4.3
      - numpy==1.24.2
      - etils==1.1.1
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - flatbuffers==23.3.3
      - googleapis-common-protos==1.59.0
      - h5py==3.8.0
      - libclang==16.0.0
      - psutil==5.9.4
      - tensorflow-io-gcs-filesystem==0.32.0
      - fastapi
      - fastapi-cli
      - opencv-python
